import type { Scenario } from "./types";

export const spikeRail: Scenario = {
  name: "spike-rail",
  seed: 12_301,
  players: [{ characterId: "captain" }],
  steps: [
    { click: "[data-lobby] .lobby-actions button:first-of-type" },
    { click: "[data-lobby] .character-select button:first-of-type" },
    { click: "[data-lobby] .lobby-panel > button:first-of-type" },
    { wait: 2_000 },
    { key: "d", downMs: 700 },
    { key: "s", downMs: 450 },
    { wait: 38_000 },
    { click: '.shop-actions button:has-text("Ready Up")' },
    { wait: 1_000 },
    { key: "a", downMs: 900 },
    { key: "w", downMs: 900 },
    { key: "d", downMs: 1_100 },
    { key: "s", downMs: 1_100 },
    { key: "a", downMs: 1_100 },
    { key: "w", downMs: 1_100 },
    { key: "d", downMs: 800 },
    { key: "s", downMs: 800 },
    { key: "a", downMs: 1_100 },
    { key: "w", downMs: 1_100 },
    { key: "d", downMs: 1_400 },
    { key: "s", downMs: 1_400 },
    { key: "a", downMs: 1_400 },
    { key: "w", downMs: 1_400 },
    { key: "d", downMs: 1_400 },
    { key: "s", downMs: 1_400 },
    { key: "a", downMs: 1_400 },
    { key: "w", downMs: 1_400 },
    { key: "d", downMs: 1_400 },
    { key: "s", downMs: 1_400 },
    { key: "a", downMs: 1_400 },
    { key: "w", downMs: 1_400 },
    { key: "d", downMs: 1_000 },
    { key: "s", downMs: 800 },
    { wait: 36_000 },
    { click: '.modules .module-btn:has-text("Build Spike Rail")' },
    { wait: 500 },
    { screenshot: "spike-rail-placed" }
  ]
};
